site_name: B&F Papers
theme:
  name: material
  custom_dir: overrides
nav:
  - Home: index.md
  - Diagram: diagram.md
  - Transformer: transformer.md

plugins:
  - search
  - mermaid2

extra:
  author_name: B&F Papers
  copyright_year: 2025